language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - tip
services:
  - riak
install:
  - cd $TRAVIS_BUILD_DIR
  - go get -d -v
  - go build -v
  - go get -v github.com/bmizerany/assert
  - go test -i
script: go test
